USE [master]
GO

/****** Object:  Database [quiescency]    Script Date: 04/22/2012 20:48:54 ******/
CREATE DATABASE [quiescency] ON  PRIMARY 
( NAME = N'quiescency', FILENAME = N'F:\учеба\ASP_EPAM\practice\hometask\Lab2\quiescency.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'quiescency_log', FILENAME = N'F:\учеба\ASP_EPAM\practice\hometask\Lab2\quiescency_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [quiescency] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [quiescency].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [quiescency] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [quiescency] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [quiescency] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [quiescency] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [quiescency] SET ARITHABORT OFF 
GO

ALTER DATABASE [quiescency] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [quiescency] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [quiescency] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [quiescency] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [quiescency] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [quiescency] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [quiescency] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [quiescency] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [quiescency] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [quiescency] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [quiescency] SET  DISABLE_BROKER 
GO

ALTER DATABASE [quiescency] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [quiescency] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [quiescency] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [quiescency] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [quiescency] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [quiescency] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [quiescency] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [quiescency] SET  READ_WRITE 
GO

ALTER DATABASE [quiescency] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [quiescency] SET  MULTI_USER 
GO

ALTER DATABASE [quiescency] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [quiescency] SET DB_CHAINING OFF 
GO

